/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trade_a_tron;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class BuyShare extends javax.swing.JFrame {
    public String share; // share here refers to username

    /**
     * Creates new form BuyShare
     */
    public BuyShare() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trademarket","root","");
            Statement stmt= con.createStatement();
            String query = "select RollNo from login where SN=1";
            ResultSet rs= stmt.executeQuery(query);
            if(rs.next()){
                share = rs.getString(1);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelShareName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldShareName = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jButtonDone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        jLabelShareName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelShareName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelShareName.setText("Share name");

        jLabelPrice.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrice.setText("Price");

        jLabelQuantity.setBackground(new java.awt.Color(0, 0, 0));
        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQuantity.setText("Quantity");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Date");

        jTextFieldShareName.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldShareName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldShareName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldShareName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShareNameActionPerformed(evt);
            }
        });

        jTextFieldPrice.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldQuantity.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldQuantity.setForeground(new java.awt.Color(255, 255, 255));

        jButtonDone.setBackground(new java.awt.Color(51, 255, 0));
        jButtonDone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonDone.setText("DONE");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        Jdate.setBackground(new java.awt.Color(0, 0, 0));
        Jdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jdate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setText("(IN CAPS)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDone)
                            .addComponent(Jdate, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelShareName)
                            .addComponent(jLabelPrice)
                            .addComponent(jLabelQuantity)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jTextFieldShareName))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelShareName)
                    .addComponent(jTextFieldShareName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDone)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldShareNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShareNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShareNameActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        int count = 0;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trademarket","root","");
            Statement stm= con.createStatement();
            //to check whether user is entering same share or not:
            String query = "SELECT * FROM myaccount WHERE ShareName='" + jTextFieldShareName.getText() + "' and SN = '"+share+"' ";
            ResultSet rs = stm.executeQuery(query);
            if(rs.next()){
                count++;
            }
            //end
            String sharename = jTextFieldShareName.getText().toUpperCase();
            String qty = jTextFieldQuantity.getText();
            String buyingprice = jTextFieldPrice.getText();
            String buyingdate = Jdate.getText();
            if((sharename.trim().isEmpty())||(qty.trim().isEmpty())||(buyingprice.trim().isEmpty())||(buyingdate.trim().isEmpty())){
                JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE FIELDS");
            }
            else{if((sharename.trim().isEmpty())||(qty.trim().isEmpty())||(buyingprice.trim().isEmpty())||(buyingdate.trim().isEmpty())){
                JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE FIELDS");
            }
                int qty1 = Integer.parseInt(qty);
                float buyingprice1 = Float.parseFloat(buyingprice);
                float totalcost = buyingprice1*qty1;
                if(count==0){
                    String query1 = "insert into myaccount(SN,ShareName,BuyingPrice,Quantity,TotalCost,Date) values('"+share+"','"+sharename+"','"+buyingprice1+"','"+qty1+"','"+totalcost+"','"+buyingdate+"') ";
                    stm.executeUpdate(query1);
                }
                else{
                    String retrieve = "select TotalCost,BuyingPrice,Quantity from myaccount where SN = '"+share+"' and ShareName='" + jTextFieldShareName.getText() + "'";
                    ResultSet rt = stm.executeQuery(retrieve);
                    float tc=0;
                    float bp = 0;
                    int qty2 = 0;
                    if(rt.next()){
                        tc = rt.getFloat(1);
                        bp = rt.getFloat(2);
                        qty2 = rt.getInt(3);
                    }
                    float tc1 = ((buyingprice1*qty1)+(bp*qty2));
                    float bpavg = tc1/(qty2+qty1);
                    int tqty = qty2+qty1;
                    String update = "update myaccount set TotalCost = '"+tc1+"', BuyingPrice = '"+bpavg+"',Quantity= '"+tqty+"',Date= '"+buyingdate+"' WHERE SN = '"+share+"'and ShareName = '"+jTextFieldShareName.getText()+"'";
                    stm.executeUpdate(update);
                    
                }
                jTextFieldShareName.setText(null);
                jTextFieldPrice.setText(null);
                jTextFieldQuantity.setText(null);
                Jdate.setText(null);
                JOptionPane.showMessageDialog(null, "DATABASE UPDATED");
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyShare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jdate;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelShareName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldShareName;
    // End of variables declaration//GEN-END:variables
}
