/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trade_a_tron;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;


/**
 *
 * @author Hp
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        jPassword1 = new javax.swing.JPasswordField();
        jLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRePassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jEmail1 = new javax.swing.JTextField();
        jEmail2 = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(247, 97, 39));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("REGISTER");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(21, 21, 21)
                .addComponent(jLabelClose)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("USERNAME");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 152, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PASSWORD");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 213, -1, -1));

        jUserName.setBackground(new java.awt.Color(0, 0, 0));
        jUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUserName.setForeground(new java.awt.Color(255, 255, 255));
        jUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNameActionPerformed(evt);
            }
        });
        jPanel5.add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 146, 294, -1));

        jPassword1.setBackground(new java.awt.Color(0, 0, 0));
        jPassword1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword1ActionPerformed(evt);
            }
        });
        jPanel5.add(jPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 210, 293, -1));

        jLastName.setBackground(new java.awt.Color(0, 0, 0));
        jLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLastName.setForeground(new java.awt.Color(255, 255, 255));
        jLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastNameActionPerformed(evt);
            }
        });
        jPanel5.add(jLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 82, 294, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("NAME");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 85, 101, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("RETYPE PASS");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 275, -1, -1));

        jRePassword.setBackground(new java.awt.Color(0, 0, 0));
        jRePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRePassword.setForeground(new java.awt.Color(255, 255, 255));
        jRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRePasswordActionPerformed(evt);
            }
        });
        jPanel5.add(jRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 272, 293, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("EMAIL ID");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 338, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("DATE OF BIRTH");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 399, -1, -1));

        jEmail1.setBackground(new java.awt.Color(0, 0, 0));
        jEmail1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEmail1.setForeground(new java.awt.Color(255, 255, 255));
        jEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmail1ActionPerformed(evt);
            }
        });
        jPanel5.add(jEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 335, 293, -1));

        jEmail2.setBackground(new java.awt.Color(0, 0, 0));
        jEmail2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEmail2.setForeground(new java.awt.Color(255, 255, 255));
        jEmail2.setToolTipText("dd/mm/yyyy");
        jEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmail2ActionPerformed(evt);
            }
        });
        jPanel5.add(jEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 293, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 138, -1, 450));

        jButtonRegister.setBackground(new java.awt.Color(0, 255, 0));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonRegister.setText("REGISTER");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 599, -1, 43));

        jReset.setBackground(new java.awt.Color(255, 0, 0));
        jReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jReset.setText("RESET");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });
        getContentPane().add(jReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 599, -1, 43));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserNameActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        int count = 0;
        String pass=jPassword1.getText();
        String rePass=jRePassword.getText();
        if(pass.equals(rePass)){
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trademarket","root","");
                Statement stmt= con.createStatement();
                String query = "SELECT * FROM users WHERE Username='" + jUserName.getText() + "'";
                ResultSet rs = stmt.executeQuery(query);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Username already taken!");
                }
                else{
                    PreparedStatement pt;
                    ResultSet rt;
                    String s="SELECT SN from Users order by SN desc limit 0,1";
                    try{
                        pt=con.prepareStatement(s);
                        rt=pt.executeQuery();
                        if(rt.next()){
                            count=rt.getInt(1);
                        }

                        String username = jUserName.getText();
                        String password = jPassword1.getText();
                        String name = jLastName.getText();
                        String email = jEmail1.getText();
                       
                        String date = jEmail2.getText(); //jEmail2 refers to the text field where we input DoB
                        if((username.trim().isEmpty())||(password.trim().isEmpty())||(name.trim().isEmpty())||(email.trim().isEmpty())||(date.trim().isEmpty())){
                            JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE DETAILS!!");
                        }
                        else{
                        String sql = "insert into users(Name, Username,Pass, Email,DoB, SN) values ( '"+name+"','"+username+"' ,'"+password+"' ,'"+email+"' ,'"+date+"','"+(count+1)+"' )";
                        PreparedStatement pstmt = con.prepareStatement(sql);
                        pstmt.executeUpdate();
                        
                        Login_Form lgf = new Login_Form();
                        lgf.setVisible(true);
                        lgf.pack();
                        lgf.setLocationRelativeTo(null);
                        JOptionPane.showMessageDialog(this, "Registered Successfully!!");
                        this.dispose();
                        con.close();}
                    }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
                }
        }catch(Exception et){
                JOptionPane.showMessageDialog(null, et);
        }}else
            JOptionPane.showMessageDialog(null, "Passwords don't match!!");
        
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastNameActionPerformed

    private void jPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword1ActionPerformed

    private void jRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRePasswordActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        jEmail1.setText(null);
        jLastName.setText(null);
        jUserName.setText(null);
        jPassword1.setText(null);
        jRePassword.setText(null);
        jEmail2.setText(null);
    }//GEN-LAST:event_jResetActionPerformed

    private void jEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmail1ActionPerformed

    private void jEmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmail2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JTextField jEmail1;
    private javax.swing.JTextField jEmail2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JTextField jLastName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jRePassword;
    private javax.swing.JButton jReset;
    private javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables
}
