/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trade_a_tron;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class SellShare extends javax.swing.JFrame {
    public String share; // SHARE  = USERNAME LOGGED IN 

    /**
     * Creates new form SellShare
     */
    public SellShare() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trademarket","root","");
            Statement stmt= con.createStatement();
            String query = "select RollNo from login where SN=1";
            ResultSet rs= stmt.executeQuery(query);
            if(rs.next()){
                share = rs.getString(1);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelShareName = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelQuantity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldShareName = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jButtonDone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelShareName.setBackground(new java.awt.Color(0, 0, 0));
        jLabelShareName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelShareName.setText("Share name");
        jPanel1.add(jLabelShareName, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 47, -1, -1));

        jLabelPrice.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrice.setText("Price");
        jPanel1.add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 115, -1, -1));

        jLabelQuantity.setBackground(new java.awt.Color(0, 0, 0));
        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelQuantity.setText("Quantity");
        jPanel1.add(jLabelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 183, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 251, -1, -1));

        jTextFieldShareName.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldShareName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldShareName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldShareName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldShareNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldShareName, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 44, 240, -1));

        jTextFieldPrice.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 112, 240, -1));

        jTextFieldQuantity.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextFieldQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 180, 240, -1));

        jButtonDone.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonDone.setText("DONE");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 292, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 1, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("-");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 1, -1, -1));

        jDate.setBackground(new java.awt.Color(0, 0, 0));
        jDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 250, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setText("(IN CAPS)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 12));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 337));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldShareNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldShareNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldShareNameActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
        int count = 0;
        int sharenamecheck = 0;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trademarket","root","");
            Statement stm= con.createStatement();
            String query = "SELECT * FROM myaccount WHERE ShareName='" + jTextFieldShareName.getText() + "' and SN = '"+share+"' ";
            ResultSet rs = stm.executeQuery(query);
            if(rs.next()){
                count++;
            }
            String sharename = jTextFieldShareName.getText().toUpperCase();
            String sqty = jTextFieldQuantity.getText();
            String sellingdate = jDate.getText();
            String sellingprice = jTextFieldPrice.getText();
            if((sharename.trim().isEmpty())||(sqty.trim().isEmpty())||(sellingprice.trim().isEmpty())||(sellingdate.trim().isEmpty())){
                JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE FIELDS");
            }
            
            
            else{
                float sellingprice1 = Float.parseFloat(sellingprice);
                int sqty1 = Integer.parseInt(sqty);

                float totalsold = sellingprice1*sqty1;//total sold when entered in gui
                String retrieve = "select TotalCost,Quantity,ShareName,BuyingPrice,SellingQuantity,SellingPrice,TotalSold from myaccount where SN = '"+share+"' and ShareName='" + jTextFieldShareName.getText() + "'";
                ResultSet rt = stm.executeQuery(retrieve);
                float btc = 0;
                int bqty = 0;
                String csn = null;
                float bp = 0;
                int sq = 0;
                float sp = 0; //retrieved selling price
                float ts1 = 0;
                if(rt.next()){
                    btc = rt.getFloat(1);
                    bqty = rt.getInt(2);
                    csn = rt.getString(3);
                    bp = rt.getFloat(4);
                    sq = rt.getInt(5);
                    sp = rt.getFloat(6);
                    ts1 = rt.getFloat(7);
                    sharenamecheck++;
                }
                float sp2 = sp*sq; // retrieved selling price total
                sq = sq+sqty1; //total selling quantity
                if((count==0) || (sq>bqty)||(sharenamecheck==0) ){
                    JOptionPane.showMessageDialog(null,"INVALID ENTRY OF SHARE OR QUANTITY ENTERED EXCEEDS THE QUANTITY BOUGHT");}
                else{
                    //float newbp;
                    
                    ts1 = ts1 + totalsold; // totalsold by user = retrieved total sold + total sold when entered in gui
                    //int remqty = bqty - sqty1;
                    
                    /*if(remqty==0){
                        newbp=0;
                    }
                    else{
                        newbp = Math.abs(((bp*bqty)-(ts))/(remqty));
                    }*/
                    //btc = newbp*remqty;
                    
                    float remprice = ts1-btc; // check profit/loss
                    float spavg = ((sp2)+(totalsold))/sq;
                    if(sq==bqty){
                        String update = "update myaccount set SellingPrice = '"+spavg+"',SellingQuantity = '"+sq+"',TotalSold = '"+totalsold+"',SellingDate = '"+sellingdate+"',ProfitLoss = '"+remprice+"',TotalSold = '"+ts1+"' WHERE ShareName='" + jTextFieldShareName.getText() + "' and SN = '"+share+"'";
                        stm.executeUpdate(update);
                    }
                    else{
                        String update = "update myaccount set SellingPrice = '"+spavg+"',SellingQuantity = '"+sq+"',TotalSold = '"+totalsold+"',SellingDate = '"+sellingdate+"',TotalSold = '"+ts1+"' WHERE ShareName='" + jTextFieldShareName.getText() + "' and SN = '"+share+"'";
                        stm.executeUpdate(update);}
                    
                    JOptionPane.showMessageDialog(null, "DATABASE UPDATED");
                    jTextFieldShareName.setText(null);
                    jTextFieldPrice.setText(null);
                    jTextFieldQuantity.setText(null);
                    jDate.setText(null);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellShare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDone;
    private javax.swing.JTextField jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelShareName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldShareName;
    // End of variables declaration//GEN-END:variables
}
